#! /bin/bash
# This script fetches data from a url with `curl`,
# stores success response in data.json and error
# response in errors.txt

URL="https://pokeapi.co/api/v2/pokemon/pikachu"

trap "echo An error cccurred; exit 1" ERR
curl -s -S $URL --fail-with-body 2> errors.txt > data.json
echo Request executed successfully
