#! /bin/bash
# This script fetches the data for a list of
# pokemons in batches.

# Catch errors in the program and log error message
trap "echo An error cccurred; exit 1" ERR

# Declare pokemon parameters
pokemon_list=('bulbasaur' 'ivysaur' 'venusaur' 'charmander' 'charmeleon')
pokemon_out_dir=pokemon_data

# Create output directory
mkdir -p $pokemon_out_dir

for pokemon in "${pokemon_list[@]}"
do
    echo "Fetching data for $pokemon..."

    file_name="$pokemon_out_dir/$pokemon.json"
    url=https://pokeapi.co/api/v2/pokemon/$pokemon
    max_retries=3
    attempt=1
    success=false

    # Make API request and retry if unsuccessful
    while (( $attempt <= $max_retries + 1)); do
        if curl -s -S $url -f 2>> errors.txt > $file_name; then
            # Stop retries if successful
            success=true
            break
        else
            # Sleep for 3s and retry
            if (($attempt <= $max_retries)); then
                echo "Retrying in 3s...($attempt)"
                sleep 3
            fi
            ((attempt++))
            continue
        fi
    done

    # Print result of request
    if $success; then
        echo "Saved to $file_name"
    else
        echo "Failed to fetch $pokemon" 
    fi

    sleep 3
done
