#! /bin/bash
# This script fetches the data for a list of
# pokemons in batches.

trap "echo An error cccurred; exit 1" ERR
pokemon_list=('bulbasaur' 'ivysaur' 'venusaur' 'charmander' 'charmeleon')
mkdir -p pokemon_data

for pokemon in "${pokemon_list[@]}"
do
    echo "Fetching data for $pokemon..."

    file_name=pokemon_data/$pokemon.json
    url=https://pokeapi.co/api/v2/pokemon/$pokemon
    curl -s -S $url --fail-with-body 2> errors.txt > $file_name

    echo "Saved to $file_name"
    sleep 5
done