#! /bin/bash
# This script fetches the data for a list of
# pokemons in batches.

trap "echo An error cccurred; exit 1" ERR
pokemon_list=('bulbasaur' 'ivysaur' 'venusaur' 'charmander' 'charmeleon')
mkdir -p pokemon_data

for pokemon in "${pokemon_list[@]}"
do
    echo "Fetching data for $pokemon..."

    file_name=pokemon_data/$pokemon.json
    url=https://pokeapi.co/api/v2/pokemon/$pokemon
    
    max_retries=3
    attempt=1
    success=false

    while (( $attempt <= $max_retries + 1)); do
        if curl -s -S $url -f 2>> errors.txt > $file_name; then
            success=true
            break
        else
            if (($attempt <= $max_retries)); then
                echo "Retrying in 3s...($attempt)"
                sleep 3
            fi
            ((attempt++))
            continue
        fi
    done

    if $success; then
        echo "Saved to $file_name"
    else
        echo "Failed to fetch $pokemon" 
    fi

    sleep 3
done
