#! /bin/bash
# This script does data extraction and processing
# with `jq`, `sed` and `awk`

path_to_file=data.json

# Extract data from json file
name=$(jq -r ".name" $path_to_file | sed 's/.*/\u&/')
type=$(jq -r ".types[].type.name" $path_to_file | sed 's/.*/\u&/')
height=$(jq -r ".height" $path_to_file)
weight=$(jq -r ".weight" $path_to_file)

## Format height and weight
formatted_height=$(echo $height | awk '{print $1/10}')
formatted_weight=$(echo $weight | awk '{print $1/10}')

## output result
echo "$name is of type $type, weighs ${formatted_weight}kg, and is ${formatted_height}m tall."