#! /bin/bash
# This scriptJ summarizes data for multiple pokemons

# Extract pokemon filenames
pokemon_file_names=$(ls pokemon_data/)
path_to_report=pokemon_report.csv

# Create report file
echo 'Name,Height (m),Weight (kg)' > $path_to_report

# Loop through each pokemon
for pk_file_name in ${pokemon_file_names[@]}
do
    full_pk_path="pokemon_data/$pk_file_name"

    # Extract json data
    name=$(jq -r '.name' $full_pk_path | sed 's/.*/\u&/')
    weight=$(jq -r '.weight' $full_pk_path | awk '{ printf("%.1f\n", $1/10) }')
    height=$(jq -r '.height' $full_pk_path | awk '{ printf("%.1f\n", $1/10) }')

    # Append to csv file
    echo $name,$height,$weight >> $path_to_report
done

# Print output
echo "CSV Report generated at: ${path_to_report}"; 
echo #newline
cat $path_to_report

# Calculate and print average
awk -F, 'BEGIN {
    sum_w=0
    sum_h=0
    count=0
} 
NR > 1 {
    sum_w+=$3
    sum_h+=$2
    count++
}
END {
    print "\nAverage Height: " sum_h/count " m\n" "Average Weight: " sum_w/count " kg"
}' $path_to_report
